services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8080"
    networks:
      - tuquiet

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - tuquiet

networks:
  tuquiet:
