services:
  - type: web
    name: tuquiet-backend
    env: java
    region: virginia
    plan: free  
    branch: WebHosting
    buildCommand: cd backend && mvn package -DskipTests
    startCommand: cd backend && java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false  
      - key: DB_USER
        sync: false  
      - key: DB_PASS
        sync: false  
      - key: ALLOWED_ORIGINS
        value: "https://tuquiet.onrender.com"
