services:
  - type: web
    name: tuquiet-backend
    env: docker
    region: virginia
    plan: free  
    branch: WebHosting
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false  
      - key: DB_USER
        sync: false  
      - key: DB_PASS
        sync: false  
      - key: ALLOWED_ORIGINS
        value: "https://tuquiet.onrender.com"
